### ISSUE TITLE
Add Validation and Unified Initialization for API URLs and Headers

### ISSUE THREAD

**Issue by 00surya** [00surya/EasyImageUpload#1]
### Problem Statement:

Currently, `theEasyImageUpload` module requires multiple separate calls to configure API URLs (`setPostImageAPIURL`, `setDeleteImageAPIURL`) and headers (`setPostImageHeaders`, `setDeleteImageHeaders`). This setup:

1. Can lead to misconfiguration if any step is missed.
2. Lacks validation, so incorrect or empty values might cause runtime errors.
3. Could be simplified for better usability and beginner-friendliness.

### Proposed Solution:

To improve usability, we propose the following changes:

1. Add URL Validation:
    - Ensure API URLs are valid, non-empty, and begin with `http` or `https`.

2. Create a Centralized Initialization Method:
    - Replace the need for separate methods by introducing a single `init` method:
   
```
EasyImageUpload.init({
              postImageAPI: 'https://your-server.com/upload',
              deleteImageAPI: 'https://your-server.com/delete',
              headers: {
                  'Content-Type': 'application/json',
                  'CSRF-Token': csrf_token,
              },
          });
```

3. Provide Default Headers:
   
     - If no headers are provided, apply a sensible default such as:

```
{
    "Content-Type": "application/json"
}
```

4. Add Error Messages:

     - Warn users with clear error messages if configurations are missing or invalid.

### Why This Is Important:
- **Usability**: Simplifies the setup process for users.
- **Reliability**: Reduces the chance of errors due to misconfiguration.
- **Beginner-Friendly**: Makes it easier for new users to get started with the module.

Steps to Implement:

1. Add validation logic to `setPostImageAPIURL` and `setDeleteImageAPIURL`.
2. Create a new `init` method to centralize configuration.
3. Update documentation to reflect the changes.

### Helpful Notes:

- Where to Look: Focus on `easy-image-upload.js`.
- Examples: Refer to the existing methods (`setPostImageAPIURL`, etc.) for how they are structured.
- If you have questions, feel free to ask in the comments!

## Friendly Note
This is a beginner-friendly issue! If you’re learning JavaScript, it’s a great way to practice skills like validation, object manipulation, and improving usability. Contributions in any form are welcome—whether it's adding validation, refactoring code, or updating the documentation. Feel free to reach out if you need any help!

**Comment by 00surya** [comment]
If you'd like to work on this issue, please comment below so I can assign it to you!

**Comment by 00surya** [comment]
If you'd like to work on this issue, please comment below so I can assign it to you!

**Comment by Choucheneeee** [comment]
Can I help simplify the configuration and add validation? Thanks!

**Comment by 00surya** [comment]
> Can I help simplify the configuration and add validation? Thanks!

Thank you for your interest! Simplifying the configuration and adding validation would be a fantastic improvement. Feel free to share your ideas or start working on it. Let me know if you have any questions or need guidance. I’m happy to help!

Looking forward to your contribution! 😊

**Comment by Choucheneeee** [comment]
I've added the function, but I'm encountering some challenges testing the code. Should I set up a server or follow a specific testing process? Any guidance would be greatly appreciated! @00surya

**Comment by 00surya** [comment]
> I've added the function, but I'm encountering some challenges testing the code. Should I set up a server or follow a specific testing process? Any guidance would be greatly appreciated! @00surya

Hi @Choucheneeee! Great to hear you’ve added the function. For testing, I’ve set up a mock server to test the image upload and deletion functionality locally. You can find detailed instructions on how to get everything running in the `testing/README.md` file. Alternatively, you can follow the testing instructions directly here: https://github.com/00surya/EasyImageUpload/tree/main?tab=readme-ov-file#testing

Let me know if you need any help with the setup!

**Comment by 00surya** [comment]
> Can I help simplify the configuration and add validation? Thanks!

The PR #2 has been successfully merged, and the issues related to validation and initialization have been resolved. I've tested the changes locally and everything is working as expected.
